### ISSUE TITLE
Fehler beim Laden der Daten

### ISSUE THREAD

**Issue by chriskli** [2KTinnovations/as24#54]
Beim Laden der Daten kommt es zu einem Fehler. Der scheint aber irgendwie sporadisch zu sein. Vorhin auf dem Mac ging es noch...

![image](https://cloud.githubusercontent.com/assets/6191778/12922285/19495932-cf51-11e5-976c-1d9df25d247f.png)

**Comment by chriskli** [comment]
beim zweiten Mal hat es dann halbwegs geklappt...
![image](https://cloud.githubusercontent.com/assets/6191778/12922411/a62dbbe0-cf51-11e5-9d77-b0dc6a4a72bf.png)

**Comment by danielkagemann** [comment]
Some helpful links on that topic

http://stackoverflow.com/questions/19810530/how-to-resolve-node-js-http-post-econnreset-error
http://www.murvinlai.com/remote-http-request.html

**Comment by danielkagemann** [comment]
after some investigation I get closer to the main problem. 
The first thing was that we only take 100 data packets from the server which results in a total number of requests of > 180.
Due to the fact that this is done in parallel it might work on Mac/Unix and totally break in windows. 
The problem here is system limitations about open file handles at one time.

First thing is to increase from 100 packets to 500 (which seems the maximum from as24).
After that we should ensure that only 10 files are open at one time. this is hard to implement but strongly required.

I checked Volkswagen ALLE which results in over 400 request for 500 data packets and even on my mac it broke.

**Comment by danielkagemann** [comment]
Reduced the number of parallel access via watcher.
Should work now. Takes some time but I was able to retrieve all car data for Ford which is about > 83000 items
