### ISSUE TITLE
Window resize doesnt effect size of Graph

### ISSUE THREAD

**Issue by Practical-DQ** [2KTinnovations/as24#56]
Resizing the window doesnt change the way the graph is resized. Only after changing a  filter is the graph redrawn to the new window size

**Comment by Practical-DQ** [comment]
Perhaps IE only bug?

**Comment by chriskli** [comment]
Screenshot please? To check if I see the same here....

**Comment by danielkagemann** [comment]
Problem is browser independent. 
Respnsive design fails for the chart due to IE. So I decided to set a fix width and height to get the same behaviour on all platforms. 
Clicking on View buttons does not redraw the chart; it is re-created so this should also be done on window resize. 

But not on each resize otherwise the performance will break down.

**Comment by danielkagemann** [comment]
done with next version
